name: 'redhat-appstudio'
spec:
  git:
    - gitOrganization: 'redhat-appstudio'
      repoName: 'service-provider-integration-operator'
      jobs:
        actions:
          monitor: true
        openshiftCI:
          monitor: true
      artifacts:
        - containerName: 'controller:next'
          containerUrl : 'quay.io/example/example:next'
      coverage:
        monitor: true
