apiVersion: v1
kind: ConfigMap
metadata:
  name: postgres-config
  namespace: appstudio-qe
  labels:
    app.kubernetes.io/component: quality-backend
    app.kubernetes.io/instance: quality-dashboard
    app.kubernetes.io/name: quality-dashboard
data:
  POSTGRES_DB: postgres
  POSTGRES_USER: admin
  POSTGRES_PASSWORD: test123
