kind: Deployment
apiVersion: apps/v1
metadata:
  name: quality-dashboard-backend
  namespace: appstudio-qe
  labels:
    app.kubernetes.io/component: quality-backend
    app.kubernetes.io/name: quality-dashboard
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/component: quality-backend
      app.kubernetes.io/name: quality-dashboard
  template:
    metadata:
      labels:
        app.kubernetes.io/component: quality-backend
        app.kubernetes.io/name: quality-dashboard
    spec:
      restartPolicy: Always
      schedulerName: default-scheduler
      terminationGracePeriodSeconds: 30
      containers:
        - name: quality-backend
          command: ["/root/qe-dashboard-backend"]
          env:
            - name: GITHUB_TOKEN
              value: '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'
          args:
            - "--config-file=/config/backend.properties"
            - "--port=8080"
          ports:
            - name: http
              containerPort: 8080
              protocol: TCP
          imagePullPolicy: Always
          image: >-
            quay.io/flacatus/dashboard-backend:next
          volumeMounts:
          - name: config
            mountPath: "/config"
            readOnly: true
      volumes:
        # You set volumes at the Pod level, then mount them into containers inside that Pod
        - name: config
          configMap:
            # Provide the name of the ConfigMap you want to mount.
            name: quality-backend-configmap
            # An array of keys from the ConfigMap to create as files
            items:
            - key: "backend.properties"
              path: "backend.properties"
