kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: postgres-pv-claim
  namespace: appstudio-qe
  labels:
    app: postgres
spec:
  storageClassName: dynamic-nfs
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 1Gi