// Code generated by entc, DO NOT EDIT.

package db

import (
	"context"
	"fmt"
	"sync"

	"github.com/flacatus/qe-dashboard-backend/pkg/storage/ent/db/codecov"
	"github.com/flacatus/qe-dashboard-backend/pkg/storage/ent/db/predicate"
	"github.com/flacatus/qe-dashboard-backend/pkg/storage/ent/db/repository"
	"github.com/google/uuid"

	"entgo.io/ent"
)

const (
	// Operation types.
	OpCreate    = ent.OpCreate
	OpDelete    = ent.OpDelete
	OpDeleteOne = ent.OpDeleteOne
	OpUpdate    = ent.OpUpdate
	OpUpdateOne = ent.OpUpdateOne

	// Node types.
	TypeCodeCov    = "CodeCov"
	TypeRepository = "Repository"
)

// CodeCovMutation represents an operation that mutates the CodeCov nodes in the graph.
type CodeCovMutation struct {
	config
	op               Op
	typ              string
	id               *uuid.UUID
	repository_name  *string
	git_organization *string
	clearedFields    map[string]struct{}
	repo_id          map[uuid.UUID]struct{}
	removedrepo_id   map[uuid.UUID]struct{}
	clearedrepo_id   bool
	done             bool
	oldValue         func(context.Context) (*CodeCov, error)
	predicates       []predicate.CodeCov
}

var _ ent.Mutation = (*CodeCovMutation)(nil)

// codecovOption allows management of the mutation configuration using functional options.
type codecovOption func(*CodeCovMutation)

// newCodeCovMutation creates new mutation for the CodeCov entity.
func newCodeCovMutation(c config, op Op, opts ...codecovOption) *CodeCovMutation {
	m := &CodeCovMutation{
		config:        c,
		op:            op,
		typ:           TypeCodeCov,
		clearedFields: make(map[string]struct{}),
	}
	for _, opt := range opts {
		opt(m)
	}
	return m
}

// withCodeCovID sets the ID field of the mutation.
func withCodeCovID(id uuid.UUID) codecovOption {
	return func(m *CodeCovMutation) {
		var (
			err   error
			once  sync.Once
			value *CodeCov
		)
		m.oldValue = func(ctx context.Context) (*CodeCov, error) {
			once.Do(func() {
				if m.done {
					err = fmt.Errorf("querying old values post mutation is not allowed")
				} else {
					value, err = m.Client().CodeCov.Get(ctx, id)
				}
			})
			return value, err
		}
		m.id = &id
	}
}

// withCodeCov sets the old CodeCov of the mutation.
func withCodeCov(node *CodeCov) codecovOption {
	return func(m *CodeCovMutation) {
		m.oldValue = func(context.Context) (*CodeCov, error) {
			return node, nil
		}
		m.id = &node.ID
	}
}

// Client returns a new `ent.Client` from the mutation. If the mutation was
// executed in a transaction (ent.Tx), a transactional client is returned.
func (m CodeCovMutation) Client() *Client {
	client := &Client{config: m.config}
	client.init()
	return client
}

// Tx returns an `ent.Tx` for mutations that were executed in transactions;
// it returns an error otherwise.
func (m CodeCovMutation) Tx() (*Tx, error) {
	if _, ok := m.driver.(*txDriver); !ok {
		return nil, fmt.Errorf("db: mutation is not running in a transaction")
	}
	tx := &Tx{config: m.config}
	tx.init()
	return tx, nil
}

// SetID sets the value of the id field. Note that this
// operation is only accepted on creation of CodeCov entities.
func (m *CodeCovMutation) SetID(id uuid.UUID) {
	m.id = &id
}

// ID returns the ID value in the mutation. Note that the ID is only available
// if it was provided to the builder or after it was returned from the database.
func (m *CodeCovMutation) ID() (id uuid.UUID, exists bool) {
	if m.id == nil {
		return
	}
	return *m.id, true
}

// SetRepositoryName sets the "repository_name" field.
func (m *CodeCovMutation) SetRepositoryName(s string) {
	m.repository_name = &s
}

// RepositoryName returns the value of the "repository_name" field in the mutation.
func (m *CodeCovMutation) RepositoryName() (r string, exists bool) {
	v := m.repository_name
	if v == nil {
		return
	}
	return *v, true
}

// OldRepositoryName returns the old "repository_name" field's value of the CodeCov entity.
// If the CodeCov object wasn't provided to the builder, the object is fetched from the database.
// An error is returned if the mutation operation is not UpdateOne, or the database query fails.
func (m *CodeCovMutation) OldRepositoryName(ctx context.Context) (v string, err error) {
	if !m.op.Is(OpUpdateOne) {
		return v, fmt.Errorf("OldRepositoryName is only allowed on UpdateOne operations")
	}
	if m.id == nil || m.oldValue == nil {
		return v, fmt.Errorf("OldRepositoryName requires an ID field in the mutation")
	}
	oldValue, err := m.oldValue(ctx)
	if err != nil {
		return v, fmt.Errorf("querying old value for OldRepositoryName: %w", err)
	}
	return oldValue.RepositoryName, nil
}

// ResetRepositoryName resets all changes to the "repository_name" field.
func (m *CodeCovMutation) ResetRepositoryName() {
	m.repository_name = nil
}

// SetGitOrganization sets the "git_organization" field.
func (m *CodeCovMutation) SetGitOrganization(s string) {
	m.git_organization = &s
}

// GitOrganization returns the value of the "git_organization" field in the mutation.
func (m *CodeCovMutation) GitOrganization() (r string, exists bool) {
	v := m.git_organization
	if v == nil {
		return
	}
	return *v, true
}

// OldGitOrganization returns the old "git_organization" field's value of the CodeCov entity.
// If the CodeCov object wasn't provided to the builder, the object is fetched from the database.
// An error is returned if the mutation operation is not UpdateOne, or the database query fails.
func (m *CodeCovMutation) OldGitOrganization(ctx context.Context) (v string, err error) {
	if !m.op.Is(OpUpdateOne) {
		return v, fmt.Errorf("OldGitOrganization is only allowed on UpdateOne operations")
	}
	if m.id == nil || m.oldValue == nil {
		return v, fmt.Errorf("OldGitOrganization requires an ID field in the mutation")
	}
	oldValue, err := m.oldValue(ctx)
	if err != nil {
		return v, fmt.Errorf("querying old value for OldGitOrganization: %w", err)
	}
	return oldValue.GitOrganization, nil
}

// ResetGitOrganization resets all changes to the "git_organization" field.
func (m *CodeCovMutation) ResetGitOrganization() {
	m.git_organization = nil
}

// AddRepoIDIDs adds the "repo_id" edge to the Repository entity by ids.
func (m *CodeCovMutation) AddRepoIDIDs(ids ...uuid.UUID) {
	if m.repo_id == nil {
		m.repo_id = make(map[uuid.UUID]struct{})
	}
	for i := range ids {
		m.repo_id[ids[i]] = struct{}{}
	}
}

// ClearRepoID clears the "repo_id" edge to the Repository entity.
func (m *CodeCovMutation) ClearRepoID() {
	m.clearedrepo_id = true
}

// RepoIDCleared reports if the "repo_id" edge to the Repository entity was cleared.
func (m *CodeCovMutation) RepoIDCleared() bool {
	return m.clearedrepo_id
}

// RemoveRepoIDIDs removes the "repo_id" edge to the Repository entity by IDs.
func (m *CodeCovMutation) RemoveRepoIDIDs(ids ...uuid.UUID) {
	if m.removedrepo_id == nil {
		m.removedrepo_id = make(map[uuid.UUID]struct{})
	}
	for i := range ids {
		delete(m.repo_id, ids[i])
		m.removedrepo_id[ids[i]] = struct{}{}
	}
}

// RemovedRepoID returns the removed IDs of the "repo_id" edge to the Repository entity.
func (m *CodeCovMutation) RemovedRepoIDIDs() (ids []uuid.UUID) {
	for id := range m.removedrepo_id {
		ids = append(ids, id)
	}
	return
}

// RepoIDIDs returns the "repo_id" edge IDs in the mutation.
func (m *CodeCovMutation) RepoIDIDs() (ids []uuid.UUID) {
	for id := range m.repo_id {
		ids = append(ids, id)
	}
	return
}

// ResetRepoID resets all changes to the "repo_id" edge.
func (m *CodeCovMutation) ResetRepoID() {
	m.repo_id = nil
	m.clearedrepo_id = false
	m.removedrepo_id = nil
}

// Where appends a list predicates to the CodeCovMutation builder.
func (m *CodeCovMutation) Where(ps ...predicate.CodeCov) {
	m.predicates = append(m.predicates, ps...)
}

// Op returns the operation name.
func (m *CodeCovMutation) Op() Op {
	return m.op
}

// Type returns the node type of this mutation (CodeCov).
func (m *CodeCovMutation) Type() string {
	return m.typ
}

// Fields returns all fields that were changed during this mutation. Note that in
// order to get all numeric fields that were incremented/decremented, call
// AddedFields().
func (m *CodeCovMutation) Fields() []string {
	fields := make([]string, 0, 2)
	if m.repository_name != nil {
		fields = append(fields, codecov.FieldRepositoryName)
	}
	if m.git_organization != nil {
		fields = append(fields, codecov.FieldGitOrganization)
	}
	return fields
}

// Field returns the value of a field with the given name. The second boolean
// return value indicates that this field was not set, or was not defined in the
// schema.
func (m *CodeCovMutation) Field(name string) (ent.Value, bool) {
	switch name {
	case codecov.FieldRepositoryName:
		return m.RepositoryName()
	case codecov.FieldGitOrganization:
		return m.GitOrganization()
	}
	return nil, false
}

// OldField returns the old value of the field from the database. An error is
// returned if the mutation operation is not UpdateOne, or the query to the
// database failed.
func (m *CodeCovMutation) OldField(ctx context.Context, name string) (ent.Value, error) {
	switch name {
	case codecov.FieldRepositoryName:
		return m.OldRepositoryName(ctx)
	case codecov.FieldGitOrganization:
		return m.OldGitOrganization(ctx)
	}
	return nil, fmt.Errorf("unknown CodeCov field %s", name)
}

// SetField sets the value of a field with the given name. It returns an error if
// the field is not defined in the schema, or if the type mismatched the field
// type.
func (m *CodeCovMutation) SetField(name string, value ent.Value) error {
	switch name {
	case codecov.FieldRepositoryName:
		v, ok := value.(string)
		if !ok {
			return fmt.Errorf("unexpected type %T for field %s", value, name)
		}
		m.SetRepositoryName(v)
		return nil
	case codecov.FieldGitOrganization:
		v, ok := value.(string)
		if !ok {
			return fmt.Errorf("unexpected type %T for field %s", value, name)
		}
		m.SetGitOrganization(v)
		return nil
	}
	return fmt.Errorf("unknown CodeCov field %s", name)
}

// AddedFields returns all numeric fields that were incremented/decremented during
// this mutation.
func (m *CodeCovMutation) AddedFields() []string {
	return nil
}

// AddedField returns the numeric value that was incremented/decremented on a field
// with the given name. The second boolean return value indicates that this field
// was not set, or was not defined in the schema.
func (m *CodeCovMutation) AddedField(name string) (ent.Value, bool) {
	return nil, false
}

// AddField adds the value to the field with the given name. It returns an error if
// the field is not defined in the schema, or if the type mismatched the field
// type.
func (m *CodeCovMutation) AddField(name string, value ent.Value) error {
	switch name {
	}
	return fmt.Errorf("unknown CodeCov numeric field %s", name)
}

// ClearedFields returns all nullable fields that were cleared during this
// mutation.
func (m *CodeCovMutation) ClearedFields() []string {
	return nil
}

// FieldCleared returns a boolean indicating if a field with the given name was
// cleared in this mutation.
func (m *CodeCovMutation) FieldCleared(name string) bool {
	_, ok := m.clearedFields[name]
	return ok
}

// ClearField clears the value of the field with the given name. It returns an
// error if the field is not defined in the schema.
func (m *CodeCovMutation) ClearField(name string) error {
	return fmt.Errorf("unknown CodeCov nullable field %s", name)
}

// ResetField resets all changes in the mutation for the field with the given name.
// It returns an error if the field is not defined in the schema.
func (m *CodeCovMutation) ResetField(name string) error {
	switch name {
	case codecov.FieldRepositoryName:
		m.ResetRepositoryName()
		return nil
	case codecov.FieldGitOrganization:
		m.ResetGitOrganization()
		return nil
	}
	return fmt.Errorf("unknown CodeCov field %s", name)
}

// AddedEdges returns all edge names that were set/added in this mutation.
func (m *CodeCovMutation) AddedEdges() []string {
	edges := make([]string, 0, 1)
	if m.repo_id != nil {
		edges = append(edges, codecov.EdgeRepoID)
	}
	return edges
}

// AddedIDs returns all IDs (to other nodes) that were added for the given edge
// name in this mutation.
func (m *CodeCovMutation) AddedIDs(name string) []ent.Value {
	switch name {
	case codecov.EdgeRepoID:
		ids := make([]ent.Value, 0, len(m.repo_id))
		for id := range m.repo_id {
			ids = append(ids, id)
		}
		return ids
	}
	return nil
}

// RemovedEdges returns all edge names that were removed in this mutation.
func (m *CodeCovMutation) RemovedEdges() []string {
	edges := make([]string, 0, 1)
	if m.removedrepo_id != nil {
		edges = append(edges, codecov.EdgeRepoID)
	}
	return edges
}

// RemovedIDs returns all IDs (to other nodes) that were removed for the edge with
// the given name in this mutation.
func (m *CodeCovMutation) RemovedIDs(name string) []ent.Value {
	switch name {
	case codecov.EdgeRepoID:
		ids := make([]ent.Value, 0, len(m.removedrepo_id))
		for id := range m.removedrepo_id {
			ids = append(ids, id)
		}
		return ids
	}
	return nil
}

// ClearedEdges returns all edge names that were cleared in this mutation.
func (m *CodeCovMutation) ClearedEdges() []string {
	edges := make([]string, 0, 1)
	if m.clearedrepo_id {
		edges = append(edges, codecov.EdgeRepoID)
	}
	return edges
}

// EdgeCleared returns a boolean which indicates if the edge with the given name
// was cleared in this mutation.
func (m *CodeCovMutation) EdgeCleared(name string) bool {
	switch name {
	case codecov.EdgeRepoID:
		return m.clearedrepo_id
	}
	return false
}

// ClearEdge clears the value of the edge with the given name. It returns an error
// if that edge is not defined in the schema.
func (m *CodeCovMutation) ClearEdge(name string) error {
	switch name {
	}
	return fmt.Errorf("unknown CodeCov unique edge %s", name)
}

// ResetEdge resets all changes to the edge with the given name in this mutation.
// It returns an error if the edge is not defined in the schema.
func (m *CodeCovMutation) ResetEdge(name string) error {
	switch name {
	case codecov.EdgeRepoID:
		m.ResetRepoID()
		return nil
	}
	return fmt.Errorf("unknown CodeCov edge %s", name)
}

// RepositoryMutation represents an operation that mutates the Repository nodes in the graph.
type RepositoryMutation struct {
	config
	op               Op
	typ              string
	id               *uuid.UUID
	repository_name  *string
	git_organization *string
	description      *string
	git_url          *string
	clearedFields    map[string]struct{}
	done             bool
	oldValue         func(context.Context) (*Repository, error)
	predicates       []predicate.Repository
}

var _ ent.Mutation = (*RepositoryMutation)(nil)

// repositoryOption allows management of the mutation configuration using functional options.
type repositoryOption func(*RepositoryMutation)

// newRepositoryMutation creates new mutation for the Repository entity.
func newRepositoryMutation(c config, op Op, opts ...repositoryOption) *RepositoryMutation {
	m := &RepositoryMutation{
		config:        c,
		op:            op,
		typ:           TypeRepository,
		clearedFields: make(map[string]struct{}),
	}
	for _, opt := range opts {
		opt(m)
	}
	return m
}

// withRepositoryID sets the ID field of the mutation.
func withRepositoryID(id uuid.UUID) repositoryOption {
	return func(m *RepositoryMutation) {
		var (
			err   error
			once  sync.Once
			value *Repository
		)
		m.oldValue = func(ctx context.Context) (*Repository, error) {
			once.Do(func() {
				if m.done {
					err = fmt.Errorf("querying old values post mutation is not allowed")
				} else {
					value, err = m.Client().Repository.Get(ctx, id)
				}
			})
			return value, err
		}
		m.id = &id
	}
}

// withRepository sets the old Repository of the mutation.
func withRepository(node *Repository) repositoryOption {
	return func(m *RepositoryMutation) {
		m.oldValue = func(context.Context) (*Repository, error) {
			return node, nil
		}
		m.id = &node.ID
	}
}

// Client returns a new `ent.Client` from the mutation. If the mutation was
// executed in a transaction (ent.Tx), a transactional client is returned.
func (m RepositoryMutation) Client() *Client {
	client := &Client{config: m.config}
	client.init()
	return client
}

// Tx returns an `ent.Tx` for mutations that were executed in transactions;
// it returns an error otherwise.
func (m RepositoryMutation) Tx() (*Tx, error) {
	if _, ok := m.driver.(*txDriver); !ok {
		return nil, fmt.Errorf("db: mutation is not running in a transaction")
	}
	tx := &Tx{config: m.config}
	tx.init()
	return tx, nil
}

// SetID sets the value of the id field. Note that this
// operation is only accepted on creation of Repository entities.
func (m *RepositoryMutation) SetID(id uuid.UUID) {
	m.id = &id
}

// ID returns the ID value in the mutation. Note that the ID is only available
// if it was provided to the builder or after it was returned from the database.
func (m *RepositoryMutation) ID() (id uuid.UUID, exists bool) {
	if m.id == nil {
		return
	}
	return *m.id, true
}

// SetRepositoryName sets the "repository_name" field.
func (m *RepositoryMutation) SetRepositoryName(s string) {
	m.repository_name = &s
}

// RepositoryName returns the value of the "repository_name" field in the mutation.
func (m *RepositoryMutation) RepositoryName() (r string, exists bool) {
	v := m.repository_name
	if v == nil {
		return
	}
	return *v, true
}

// OldRepositoryName returns the old "repository_name" field's value of the Repository entity.
// If the Repository object wasn't provided to the builder, the object is fetched from the database.
// An error is returned if the mutation operation is not UpdateOne, or the database query fails.
func (m *RepositoryMutation) OldRepositoryName(ctx context.Context) (v string, err error) {
	if !m.op.Is(OpUpdateOne) {
		return v, fmt.Errorf("OldRepositoryName is only allowed on UpdateOne operations")
	}
	if m.id == nil || m.oldValue == nil {
		return v, fmt.Errorf("OldRepositoryName requires an ID field in the mutation")
	}
	oldValue, err := m.oldValue(ctx)
	if err != nil {
		return v, fmt.Errorf("querying old value for OldRepositoryName: %w", err)
	}
	return oldValue.RepositoryName, nil
}

// ResetRepositoryName resets all changes to the "repository_name" field.
func (m *RepositoryMutation) ResetRepositoryName() {
	m.repository_name = nil
}

// SetGitOrganization sets the "git_organization" field.
func (m *RepositoryMutation) SetGitOrganization(s string) {
	m.git_organization = &s
}

// GitOrganization returns the value of the "git_organization" field in the mutation.
func (m *RepositoryMutation) GitOrganization() (r string, exists bool) {
	v := m.git_organization
	if v == nil {
		return
	}
	return *v, true
}

// OldGitOrganization returns the old "git_organization" field's value of the Repository entity.
// If the Repository object wasn't provided to the builder, the object is fetched from the database.
// An error is returned if the mutation operation is not UpdateOne, or the database query fails.
func (m *RepositoryMutation) OldGitOrganization(ctx context.Context) (v string, err error) {
	if !m.op.Is(OpUpdateOne) {
		return v, fmt.Errorf("OldGitOrganization is only allowed on UpdateOne operations")
	}
	if m.id == nil || m.oldValue == nil {
		return v, fmt.Errorf("OldGitOrganization requires an ID field in the mutation")
	}
	oldValue, err := m.oldValue(ctx)
	if err != nil {
		return v, fmt.Errorf("querying old value for OldGitOrganization: %w", err)
	}
	return oldValue.GitOrganization, nil
}

// ResetGitOrganization resets all changes to the "git_organization" field.
func (m *RepositoryMutation) ResetGitOrganization() {
	m.git_organization = nil
}

// SetDescription sets the "description" field.
func (m *RepositoryMutation) SetDescription(s string) {
	m.description = &s
}

// Description returns the value of the "description" field in the mutation.
func (m *RepositoryMutation) Description() (r string, exists bool) {
	v := m.description
	if v == nil {
		return
	}
	return *v, true
}

// OldDescription returns the old "description" field's value of the Repository entity.
// If the Repository object wasn't provided to the builder, the object is fetched from the database.
// An error is returned if the mutation operation is not UpdateOne, or the database query fails.
func (m *RepositoryMutation) OldDescription(ctx context.Context) (v string, err error) {
	if !m.op.Is(OpUpdateOne) {
		return v, fmt.Errorf("OldDescription is only allowed on UpdateOne operations")
	}
	if m.id == nil || m.oldValue == nil {
		return v, fmt.Errorf("OldDescription requires an ID field in the mutation")
	}
	oldValue, err := m.oldValue(ctx)
	if err != nil {
		return v, fmt.Errorf("querying old value for OldDescription: %w", err)
	}
	return oldValue.Description, nil
}

// ResetDescription resets all changes to the "description" field.
func (m *RepositoryMutation) ResetDescription() {
	m.description = nil
}

// SetGitURL sets the "git_url" field.
func (m *RepositoryMutation) SetGitURL(s string) {
	m.git_url = &s
}

// GitURL returns the value of the "git_url" field in the mutation.
func (m *RepositoryMutation) GitURL() (r string, exists bool) {
	v := m.git_url
	if v == nil {
		return
	}
	return *v, true
}

// OldGitURL returns the old "git_url" field's value of the Repository entity.
// If the Repository object wasn't provided to the builder, the object is fetched from the database.
// An error is returned if the mutation operation is not UpdateOne, or the database query fails.
func (m *RepositoryMutation) OldGitURL(ctx context.Context) (v string, err error) {
	if !m.op.Is(OpUpdateOne) {
		return v, fmt.Errorf("OldGitURL is only allowed on UpdateOne operations")
	}
	if m.id == nil || m.oldValue == nil {
		return v, fmt.Errorf("OldGitURL requires an ID field in the mutation")
	}
	oldValue, err := m.oldValue(ctx)
	if err != nil {
		return v, fmt.Errorf("querying old value for OldGitURL: %w", err)
	}
	return oldValue.GitURL, nil
}

// ResetGitURL resets all changes to the "git_url" field.
func (m *RepositoryMutation) ResetGitURL() {
	m.git_url = nil
}

// Where appends a list predicates to the RepositoryMutation builder.
func (m *RepositoryMutation) Where(ps ...predicate.Repository) {
	m.predicates = append(m.predicates, ps...)
}

// Op returns the operation name.
func (m *RepositoryMutation) Op() Op {
	return m.op
}

// Type returns the node type of this mutation (Repository).
func (m *RepositoryMutation) Type() string {
	return m.typ
}

// Fields returns all fields that were changed during this mutation. Note that in
// order to get all numeric fields that were incremented/decremented, call
// AddedFields().
func (m *RepositoryMutation) Fields() []string {
	fields := make([]string, 0, 4)
	if m.repository_name != nil {
		fields = append(fields, repository.FieldRepositoryName)
	}
	if m.git_organization != nil {
		fields = append(fields, repository.FieldGitOrganization)
	}
	if m.description != nil {
		fields = append(fields, repository.FieldDescription)
	}
	if m.git_url != nil {
		fields = append(fields, repository.FieldGitURL)
	}
	return fields
}

// Field returns the value of a field with the given name. The second boolean
// return value indicates that this field was not set, or was not defined in the
// schema.
func (m *RepositoryMutation) Field(name string) (ent.Value, bool) {
	switch name {
	case repository.FieldRepositoryName:
		return m.RepositoryName()
	case repository.FieldGitOrganization:
		return m.GitOrganization()
	case repository.FieldDescription:
		return m.Description()
	case repository.FieldGitURL:
		return m.GitURL()
	}
	return nil, false
}

// OldField returns the old value of the field from the database. An error is
// returned if the mutation operation is not UpdateOne, or the query to the
// database failed.
func (m *RepositoryMutation) OldField(ctx context.Context, name string) (ent.Value, error) {
	switch name {
	case repository.FieldRepositoryName:
		return m.OldRepositoryName(ctx)
	case repository.FieldGitOrganization:
		return m.OldGitOrganization(ctx)
	case repository.FieldDescription:
		return m.OldDescription(ctx)
	case repository.FieldGitURL:
		return m.OldGitURL(ctx)
	}
	return nil, fmt.Errorf("unknown Repository field %s", name)
}

// SetField sets the value of a field with the given name. It returns an error if
// the field is not defined in the schema, or if the type mismatched the field
// type.
func (m *RepositoryMutation) SetField(name string, value ent.Value) error {
	switch name {
	case repository.FieldRepositoryName:
		v, ok := value.(string)
		if !ok {
			return fmt.Errorf("unexpected type %T for field %s", value, name)
		}
		m.SetRepositoryName(v)
		return nil
	case repository.FieldGitOrganization:
		v, ok := value.(string)
		if !ok {
			return fmt.Errorf("unexpected type %T for field %s", value, name)
		}
		m.SetGitOrganization(v)
		return nil
	case repository.FieldDescription:
		v, ok := value.(string)
		if !ok {
			return fmt.Errorf("unexpected type %T for field %s", value, name)
		}
		m.SetDescription(v)
		return nil
	case repository.FieldGitURL:
		v, ok := value.(string)
		if !ok {
			return fmt.Errorf("unexpected type %T for field %s", value, name)
		}
		m.SetGitURL(v)
		return nil
	}
	return fmt.Errorf("unknown Repository field %s", name)
}

// AddedFields returns all numeric fields that were incremented/decremented during
// this mutation.
func (m *RepositoryMutation) AddedFields() []string {
	return nil
}

// AddedField returns the numeric value that was incremented/decremented on a field
// with the given name. The second boolean return value indicates that this field
// was not set, or was not defined in the schema.
func (m *RepositoryMutation) AddedField(name string) (ent.Value, bool) {
	return nil, false
}

// AddField adds the value to the field with the given name. It returns an error if
// the field is not defined in the schema, or if the type mismatched the field
// type.
func (m *RepositoryMutation) AddField(name string, value ent.Value) error {
	switch name {
	}
	return fmt.Errorf("unknown Repository numeric field %s", name)
}

// ClearedFields returns all nullable fields that were cleared during this
// mutation.
func (m *RepositoryMutation) ClearedFields() []string {
	return nil
}

// FieldCleared returns a boolean indicating if a field with the given name was
// cleared in this mutation.
func (m *RepositoryMutation) FieldCleared(name string) bool {
	_, ok := m.clearedFields[name]
	return ok
}

// ClearField clears the value of the field with the given name. It returns an
// error if the field is not defined in the schema.
func (m *RepositoryMutation) ClearField(name string) error {
	return fmt.Errorf("unknown Repository nullable field %s", name)
}

// ResetField resets all changes in the mutation for the field with the given name.
// It returns an error if the field is not defined in the schema.
func (m *RepositoryMutation) ResetField(name string) error {
	switch name {
	case repository.FieldRepositoryName:
		m.ResetRepositoryName()
		return nil
	case repository.FieldGitOrganization:
		m.ResetGitOrganization()
		return nil
	case repository.FieldDescription:
		m.ResetDescription()
		return nil
	case repository.FieldGitURL:
		m.ResetGitURL()
		return nil
	}
	return fmt.Errorf("unknown Repository field %s", name)
}

// AddedEdges returns all edge names that were set/added in this mutation.
func (m *RepositoryMutation) AddedEdges() []string {
	edges := make([]string, 0, 0)
	return edges
}

// AddedIDs returns all IDs (to other nodes) that were added for the given edge
// name in this mutation.
func (m *RepositoryMutation) AddedIDs(name string) []ent.Value {
	return nil
}

// RemovedEdges returns all edge names that were removed in this mutation.
func (m *RepositoryMutation) RemovedEdges() []string {
	edges := make([]string, 0, 0)
	return edges
}

// RemovedIDs returns all IDs (to other nodes) that were removed for the edge with
// the given name in this mutation.
func (m *RepositoryMutation) RemovedIDs(name string) []ent.Value {
	return nil
}

// ClearedEdges returns all edge names that were cleared in this mutation.
func (m *RepositoryMutation) ClearedEdges() []string {
	edges := make([]string, 0, 0)
	return edges
}

// EdgeCleared returns a boolean which indicates if the edge with the given name
// was cleared in this mutation.
func (m *RepositoryMutation) EdgeCleared(name string) bool {
	return false
}

// ClearEdge clears the value of the edge with the given name. It returns an error
// if that edge is not defined in the schema.
func (m *RepositoryMutation) ClearEdge(name string) error {
	return fmt.Errorf("unknown Repository unique edge %s", name)
}

// ResetEdge resets all changes to the edge with the given name in this mutation.
// It returns an error if the edge is not defined in the schema.
func (m *RepositoryMutation) ResetEdge(name string) error {
	return fmt.Errorf("unknown Repository edge %s", name)
}
